#ifndef DEX2C_HPP_
#define DEX2C_HPP_

#include <jni.h>

void Java_I__0115f_0fe00_0fe03__0003cinit_0003e__Lbin_nt_main_App_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_I__0115f_0fe01_0fe01__0003cinit_0003e__Lbin_nt_main_BaseActivity_2LI__0115f_0fe0e_0fe00_2Landroid_graphics_Bitmap_2_3F_3Z(JNIEnv* env, jobject thiz, jobject p0, jobject p1, jobject p2, jarray p3, jarray p4);
void Java_I__0115f_0fe01_0fe0c__0115f_0fe03_0fe01__Lbin_nt_editor_widget_CodeEditor_2FF(JNIEnv* env, jclass clazz, jobject p0, jfloat p1, jfloat p2);
void Java_I__0115f_0fe01_0fe0e__0003cinit_0003e__Lbin_nt_fragments_FileBrowserFragment_2Ljava_io_File_2(JNIEnv* env, jobject thiz, jobject p0, jobject p1);
void Java_I__0115f_0fe03_0fe01__0115f_0fe04_0fe01__Lbin_nt_editor_widget_CodeEditor_2FF(JNIEnv* env, jclass clazz, jobject p0, jfloat p1, jfloat p2);
void Java_I__0115f_0fe03_0fe06__0003cinit_0003e__Lbin_nt_fragments_FileBrowserFragment_2Z(JNIEnv* env, jobject thiz, jobject p0, jboolean p1);
void Java_I__0115f_0fe03_0fe07__0003cinit_0003e__Lbin_nt_main_CrashActivity_2I(JNIEnv* env, jobject thiz, jobject p0, jint p1);
void Java_I__0115f_0fe03_0fe0d__0003cinit_0003e__Lbin_nt_fragments_FileBrowserFragment_2Landroid_content_Context_2ZILjava_lang_String_2Ljava_io_File_2Ljava_lang_String_2Ljava_lang_String_2(JNIEnv* env, jobject thiz, jobject p0, jobject p1, jboolean p2, jint p3, jobject p4, jobject p5, jobject p6, jobject p7);
void Java_I__0115f_0fe04_0fe00__0003cinit_0003e__Lbin_nt_fragments_FileBrowserFragment_2Ljava_lang_Object_2Ljava_io_Serializable_2Ljava_io_Serializable_2(JNIEnv* env, jobject thiz, jobject p0, jobject p1, jobject p2, jobject p3);
void Java_I__0115f_0fe04_0fe0d__0003cinit_0003e__Lbin_nt_fragments_FileBrowserFragment_2Landroid_net_Uri_2Ljava_lang_String_2Ljava_util_List_2LI__0115f_0fe0b_0fe0b_2Landroid_widget_EditText_2Landroid_widget_EditText_2Landroid_widget_EditText_2(JNIEnv* env, jobject thiz, jobject p0, jobject p1, jobject p2, jobject p3, jobject p4, jobject p5, jobject p6, jobject p7);
void Java_I__0115f_0fe04_0fe0e__0003cinit_0003e__Lbin_nt_fragments_FileBrowserFragment_2_3ZLjava_util_List_2Ljava_lang_String_2(JNIEnv* env, jobject thiz, jobject p0, jarray p1, jobject p2, jobject p3);
void Java_I__0115f_0fe05_0fe01__0115f_0fe06_0fe01__Lbin_nt_editor_widget_CodeEditor_2(JNIEnv* env, jclass clazz, jobject p0);
void Java_I__0115f_0fe05_0fe0d__0003cinit_0003e__Lbin_nt_fragments_FileBrowserFragment_2Z(JNIEnv* env, jobject thiz, jobject p0, jboolean p1);
void Java_I__0115f_0fe06_0fe01__0115f_0fe03_0fe01__Lbin_nt_editor_widget_CodeEditor_2(JNIEnv* env, jclass clazz, jobject p0);
void Java_I__0115f_0fe06_0fe03__0003cinit_0003e__Lbin_nt_fragments_FileBrowserFragment_2Landroid_content_Context_2Ljava_io_File_2LI__0115f_0fe0d_0fe0e_2(JNIEnv* env, jobject thiz, jobject p0, jobject p1, jobject p2, jobject p3);
void Java_I__0115f_0fe06_0fe03__0003cinit_0003e__Lbin_nt_fragments_FileBrowserFragment_2Ljava_util_ArrayList_2Ljava_io_File_2Ljava_lang_String_2(JNIEnv* env, jobject thiz, jobject p0, jobject p1, jobject p2, jobject p3);
void Java_I__0115f_0fe06_0fe03__0003cinit_0003e__Lbin_nt_fragments_FileBrowserFragment_2_3ZLjava_lang_String_2Ljava_io_File_2(JNIEnv* env, jobject thiz, jobject p0, jarray p1, jobject p2, jobject p3);
void Java_I__0115f_0fe06_0fe0d__0003cinit_0003e__Lbin_nt_fragments_FileBrowserFragment_2IILjava_lang_String_2Ljava_lang_String_2ZJLjava_util_ArrayList_2Ljava_lang_String_2(JNIEnv* env, jobject thiz, jobject p0, jint p1, jint p2, jobject p3, jobject p4, jboolean p5, jlong p6, jobject p7, jobject p8);
void Java_I__0115f_0fe07_0fe0d__0003cinit_0003e__Lbin_nt_fragments_FileBrowserFragment_2Ljava_io_File_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2LI__0115f_0fe0b_0fe0b_2Landroid_content_Context_2Ljava_lang_String_2Ljava_util_List_2(JNIEnv* env, jobject thiz, jobject p0, jobject p1, jobject p2, jobject p3, jobject p4, jobject p5, jobject p6, jobject p7, jobject p8);
void Java_I__0115f_0fe08_0fe0c__0003cinit_0003e__Lbin_nt_editor_widget_CodeEditor_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_I__0115f_0fe08_0fe0d__0003cinit_0003e__Lbin_nt_fragments_FileBrowserFragment_2Ljava_lang_String_2ZLandroid_content_Context_2IIZ(JNIEnv* env, jobject thiz, jobject p0, jobject p1, jboolean p2, jobject p3, jint p4, jint p5, jboolean p6);
void Java_I__0115f_0fe08_0fe0e__0003cinit_0003e__Lbin_nt_fragments_FileBrowserFragment_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_I__0115f_0fe09_0fe05__0003cinit_0003e__Lbin_nt_editor_widget_CodeEditor_2Ljava_lang_Runnable_2I(JNIEnv* env, jobject thiz, jobject p0, jobject p1, jint p2);
void Java_I__0115f_0fe09_0fe0d__0003cinit_0003e__Lbin_nt_fragments_FileBrowserFragment_2Landroid_content_Context_2Ljava_lang_String_2LI__0115f_0fe0f_0fe01_2LI__0115f_0fe0e_0fe0e_2Z(JNIEnv* env, jobject thiz, jobject p0, jobject p1, jobject p2, jobject p3, jobject p4, jboolean p5);
void Java_I__0115f_0fe0a_0fe0a__0003cinit_0003e__Lbin_nt_editor_widget_CodeEditor_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_I__0115f_0fe0a_0fe0b__0003cinit_0003e__Lbin_nt_fragments_FileBrowserFragment_2Landroid_content_Context_2Ljava_lang_String_2Ljava_lang_Object_2I(JNIEnv* env, jobject thiz, jobject p0, jobject p1, jobject p2, jobject p3, jint p4);
void Java_I__0115f_0fe0a_0fe0e__0003cinit_0003e__Lbin_nt_fragments_FileBrowserFragment_2LI__0115f_0fe0e_0fe0e_2Z(JNIEnv* env, jobject thiz, jobject p0, jobject p1, jboolean p2);
void Java_I__0115f_0fe0b_0fe0d__0003cinit_0003e__Lbin_nt_fragments_FileBrowserFragment_2LI__0115f_0fe0e_0fe0e_2I(JNIEnv* env, jobject thiz, jobject p0, jobject p1, jint p2);
void Java_I__0115f_0fe0c_0fe0d__0003cinit_0003e__Lbin_nt_fragments_FileBrowserFragment_2Ljava_io_File_2Ljava_io_File_2LI__0115f_0fe02_0fe04_2LI__0115f_0fe0e_0fe0e_2Landroid_content_Context_2Ljava_lang_String_2Ljava_lang_String_2(JNIEnv* env, jobject thiz, jobject p0, jobject p1, jobject p2, jobject p3, jobject p4, jobject p5, jobject p6, jobject p7);
void Java_I__0115f_0fe0d_0fe0c__0003cinit_0003e__Lbin_nt_ui_fastscroll_FastScrollerRecyclerView_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_I__0115f_0fe0e_0fe00__0003cinit_0003e__Lbin_nt_main_BaseActivity_2Landroid_graphics_Bitmap_2Landroid_graphics_Paint_2_3Landroid_graphics_Rect_2_3FLandroid_graphics_Paint_2(JNIEnv* env, jobject thiz, jobject p0, jobject p1, jobject p2, jarray p3, jarray p4, jobject p5);
void Java_I__0115f_0fe0e_0fe0d__0003cinit_0003e__Lbin_nt_fragments_FileBrowserFragment_2Ljava_lang_String_2_3Z_3Ljava_lang_String_2Ljava_lang_String_2(JNIEnv* env, jobject thiz, jobject p0, jobject p1, jarray p2, jarray p3, jobject p4);
void Java_I__0115f_0fe0f_0fe0d__0003cinit_0003e__Lbin_nt_fragments_FileBrowserFragment_2Ljava_lang_String_2LI__0115f_0fe0e_0fe0e_2I(JNIEnv* env, jobject thiz, jobject p0, jobject p1, jobject p2, jint p3);
void Java_I__01160_0fe00_0fe02__0003cinit_0003e__Lbin_nt_main_MainActivity_2I(JNIEnv* env, jobject thiz, jobject p0, jint p1);
void Java_I__01160_0fe01_0fe04__0003cinit_0003e__Lbin_nt_main_PhotoViewerActivity_2I(JNIEnv* env, jobject thiz, jobject p0, jint p1);
void Java_I__01160_0fe02_0fe02__0003cinit_0003e__Lbin_nt_main_MainActivity_2I(JNIEnv* env, jobject thiz, jobject p0, jint p1);
void Java_I__01160_0fe02_0fe03__0003cinit_0003e__Lbin_nt_editor_widget_CodeEditor_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_I__01160_0fe03_0fe02__0003cinit_0003e__Lbin_nt_main_MainActivity_2Ljava_io_File_2Ljava_util_ArrayList_2I(JNIEnv* env, jobject thiz, jobject p0, jobject p1, jobject p2, jint p3);
void Java_I__01160_0fe04_0fe02__0003cinit_0003e__Lbin_nt_main_MainActivity_2ILjava_lang_String_2ILjava_lang_String_2(JNIEnv* env, jobject thiz, jobject p0, jint p1, jobject p2, jint p3, jobject p4);
void Java_I__01160_0fe04_0fe09__0115f_0fe0b_0fe02__Lbin_nt_main_BaseActivity_2II_3Landroid_graphics_Rect_2LI__0115f_0fe08_0fe08_2(JNIEnv* env, jclass clazz, jobject p0, jint p1, jint p2, jarray p3, jobject p4);
void Java_I__01160_0fe05_0fe02__0003cinit_0003e__Lbin_nt_main_MainActivity_2Landroid_view_MenuItem_2Landroid_view_View_2I(JNIEnv* env, jobject thiz, jobject p0, jobject p1, jobject p2, jint p3);
void Java_I__01160_0fe06_0fe02__0003cinit_0003e__Lbin_nt_main_MainActivity_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_I__01160_0fe06_0fe08__0003cinit_0003e__Lbin_nt_editor_widget_CodeEditor_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_I__01160_0fe06_0fe09__0003cinit_0003e__Lbin_nt_main_TextEditorActivity_2I(JNIEnv* env, jobject thiz, jobject p0, jint p1);
void Java_I__01160_0fe07_0fe09__0003cinit_0003e__Lbin_nt_main_TextEditorActivity_2I(JNIEnv* env, jobject thiz, jobject p0, jint p1);
void Java_I__01160_0fe08_0fe02__0003cinit_0003e__Lbin_nt_main_MainActivity_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_I__01160_0fe08_0fe09__0003cinit_0003e__Lbin_nt_main_TextEditorActivity_2II(JNIEnv* env, jobject thiz, jobject p0, jint p1, jint p2);
void Java_I__01160_0fe0a_0fe09__0003cinit_0003e__Lbin_nt_main_TextEditorActivity_2I(JNIEnv* env, jobject thiz, jobject p0, jint p1);
void Java_I__01160_0fe0c_0fe09__0003cinit_0003e__Lbin_nt_main_TextEditorActivity_2Landroid_widget_ProgressBar_2I(JNIEnv* env, jobject thiz, jobject p0, jobject p1, jint p2);
jobject Java_I__01160_0fe0d_0fe08__0115f_0fe02_0fe00__Lbin_nt_main_TextEditorActivity_2(JNIEnv* env, jclass clazz, jobject p0);
void Java_I__01160_0fe0d_0fe09__0003cinit_0003e__Lbin_nt_main_TextEditorActivity_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_I__01160_0fe0d_0fe0a__0003cinit_0003e__ILandroid_graphics_Paint_00024FontMetricsInt_2IIIIIIFLbin_nt_editor_widget_CodeEditor_2LI__0115f_0fe0c_0fe09_2LI__01160_0fe0e_0fe03_2LI__01160_0fe0e_0fe03_2Landroid_graphics_Paint_00024FontMetricsInt_2(JNIEnv* env, jobject thiz, jint p0, jobject p1, jint p2, jint p3, jint p4, jint p5, jint p6, jint p7, jfloat p8, jobject p9, jobject p10, jobject p11, jobject p12, jobject p13);
jobject Java_I__01160_0fe0e_0fe06__0115f_0fe01_0fe00__Lbin_nt_editor_widget_CodeEditor_2LI__0115f_0fe02_0fe05_2(JNIEnv* env, jobject thiz, jobject p0, jobject p1);
void Java_androidx_core_content_ContextCompat__0115f_0fe07_0fe00__Landroid_content_Context_2Lbin_nt_xapk_ApkInstallReceiver_2Landroid_content_IntentFilter_2(JNIEnv* env, jclass clazz, jobject p0, jobject p1, jobject p2);
void Java_bin_nt_main_App__0003cinit_0003e__(JNIEnv* env, jobject thiz);
void Java_bin_nt_main_App__0115f_0fe00_0fe00__Ljava_lang_String_2(JNIEnv* env, jclass clazz, jobject p0);
jobject Java_bin_nt_main_App__0115f_0fe03_0fe00__(JNIEnv* env, jclass clazz);
jobject Java_bin_nt_main_App__0115f_0fe04_0fe00__Ljava_lang_String_2(JNIEnv* env, jclass clazz, jobject p0);
void Java_bin_nt_main_App__0115f_0fe07_0fe00__Ljava_lang_String_2(JNIEnv* env, jobject thiz, jobject p0);
jobject Java_bin_nt_ui_PanelView_getLinearLayoutManager__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_ui_PanelView_getRecyclerView__(JNIEnv* env, jobject thiz);
void Java_bin_nt_ui_PanelView_setJellyColor__I(JNIEnv* env, jobject thiz, jint p0);
void Java_bin_nt_ui_PanelView_setOnPanelTouchedListener__LI__01160_0fe0f_0fe03_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_bin_nt_ui_PanelView_setPanelBackground__I(JNIEnv* env, jobject thiz, jint p0);
void Java_bin_nt_ui_PanelView_setPullToRefreshListener__LI__01160_0fe01_0fe05_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_bin_nt_ui_PanelView_setRefreshing__Z(JNIEnv* env, jobject thiz, jboolean p0);
void Java_bin_nt_ui_PanelView__0115f_0fe01_0fe00__LI__0115f_0fe01_0fe0d_2Z(JNIEnv* env, jobject thiz, jobject p0, jboolean p1);
void Java_bin_nt_ui_animation_InnerShadow__0003cinit_0003e__Landroid_content_Context_2Landroid_util_AttributeSet_2(JNIEnv* env, jobject thiz, jobject p0, jobject p1);
void Java_bin_nt_ui_animation_InnerShadow_onDraw__Landroid_graphics_Canvas_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_bin_nt_xapk_ApkInstallReceiver__0003cinit_0003e__(JNIEnv* env, jobject thiz);
void Java_I__0115f_0fe00_0fe07__0003cinit_0003e__Lbin_nt_editor_widget_CodeEditor_2ILI__0115f_0fe02_0fe05_2LI__0115f_0fe02_0fe05_2Ljava_lang_CharSequence_2Z(JNIEnv* env, jobject thiz, jobject p0, jint p1, jobject p2, jobject p3, jobject p4, jboolean p5);
void Java_I__0115f_0fe00_0fe0c__0003cinit_0003e__Lbin_nt_editor_widget_CodeEditor_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_I__0115f_0fe02_0fe0d__0003cinit_0003e__Lbin_nt_fragments_FileBrowserFragment_2I(JNIEnv* env, jobject thiz, jobject p0, jint p1);
void Java_I__0115f_0fe04_0fe07__0003cinit_0003e__Lbin_nt_editor_widget_CodeEditor_2Landroid_view_ContextMenu_2LI__0115f_0fe02_0fe05_2(JNIEnv* env, jobject thiz, jobject p0, jobject p1, jobject p2);
void Java_I__0115f_0fe04_0fe0a__0003cinit_0003e__Lbin_nt_editor_widget_CodeEditor_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_I__0115f_0fe05_0fe0a__0003cinit_0003e__Lbin_nt_editor_widget_CodeEditor_2Z(JNIEnv* env, jobject thiz, jobject p0, jboolean p1);
void Java_I__0115f_0fe05_0fe0f__0003cinit_0003e__Lbin_nt_editor_widget_CodeEditor_2IZ(JNIEnv* env, jobject thiz, jobject p0, jint p1, jboolean p2);
void Java_I__0115f_0fe06_0fe0e__0003cinit_0003e__Lbin_nt_editor_widget_CodeEditor_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_I__0115f_0fe06_0fe0e__0003cinit_0003e__Lbin_nt_fragments_FileBrowserFragment_2Ljava_io_Serializable_2Ljava_lang_Object_2(JNIEnv* env, jobject thiz, jobject p0, jobject p1, jobject p2);
void Java_I__0115f_0fe09_0fe0e__0003cinit_0003e__Lbin_nt_fragments_FileBrowserFragment_2LI__0115f_0fe01_0fe0d_2LI__0115f_0fe01_0fe0d_2(JNIEnv* env, jobject thiz, jobject p0, jobject p1, jobject p2);
void Java_I__0115f_0fe0a_0fe0d__0003cinit_0003e__Lbin_nt_fragments_FileBrowserFragment_2LI__0115f_0fe0e_0fe0e_2Z(JNIEnv* env, jobject thiz, jobject p0, jobject p1, jboolean p2);
void Java_I__0115f_0fe0b_0fe09__0003cinit_0003e__Lbin_nt_editor_widget_CodeEditor_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_I__0115f_0fe0c_0fe04__0003cinit_0003e__Lbin_nt_editor_widget_CodeEditor_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_I__0115f_0fe0c_0fe0a__0003cinit_0003e__Lbin_nt_editor_widget_CodeEditor_2Landroid_view_KeyEvent_2LI__0115f_0fe0b_0fe0a_2(JNIEnv* env, jobject thiz, jobject p0, jobject p1, jobject p2);
void Java_I__0115f_0fe0d_0fe01__0003cinit_0003e__Landroidx_drawerlayout_widget_DrawerLayout_2Landroid_widget_ImageView_2Landroid_widget_LinearLayout_2Lcom_google_android_material_bottomnavigation_BottomNavigationView_2Landroid_widget_LinearLayout_2Landroidx_drawerlayout_widget_DrawerLayout_2Landroidx_recyclerview_widget_RecyclerView_2Landroidx_appcompat_widget_Toolbar_2Landroid_widget_FrameLayout_2Landroidx_coordinatorlayout_widget_CoordinatorLayout_2Landroid_widget_ImageView_2Lbin_nt_ui_HackyViewPager_2Landroid_view_View_2Lcom_google_android_material_tabs_TabLayout_2Landroid_widget_ImageView_2Landroidx_appcompat_widget_Toolbar_2(JNIEnv* env, jobject thiz, jobject p0, jobject p1, jobject p2, jobject p3, jobject p4, jobject p5, jobject p6, jobject p7, jobject p8, jobject p9, jobject p10, jobject p11, jobject p12, jobject p13, jobject p14, jobject p15);
void Java_I__0115f_0fe0e_0fe01__0003cinit_0003e__Landroid_widget_FrameLayout_2Landroid_widget_LinearLayout_2Landroid_widget_FrameLayout_2Landroid_widget_TextView_2Lbin_nt_ui_HackyViewPager_2Landroid_widget_CheckBox_2Landroid_widget_ImageButton_2Landroidx_appcompat_widget_Toolbar_2Landroid_widget_FrameLayout_2(JNIEnv* env, jobject thiz, jobject p0, jobject p1, jobject p2, jobject p3, jobject p4, jobject p5, jobject p6, jobject p7, jobject p8);
void Java_I__0115f_0fe0e_0fe0a__0003cinit_0003e__Lbin_nt_editor_widget_CodeEditor_2LI__0115f_0fe02_0fe05_2Landroid_view_MotionEvent_2(JNIEnv* env, jobject thiz, jobject p0, jobject p1, jobject p2);
void Java_I__0115f_0fe0e_0fe0c__0003cinit_0003e__Lbin_nt_ui_fastscroll_FastScrollerRecyclerView_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_I__0115f_0fe0f_0fe01__0003cinit_0003e__Lbin_nt_fragments_FileBrowserFragment_2LI__01160_0fe09_0fe0c_2(JNIEnv* env, jobject thiz, jobject p0, jobject p1);
jboolean Java_I__0115f_0fe0f_0fe01__0115f_0fe02_0fe00__Lbin_nt_editor_widget_CodeEditor_2LI__0115f_0fe05_0fe07_2LI__0115f_0fe0d_0fe06_2LI__0115f_0fe0c_0fe0a_2LI__01160_0fe0b_0fe00_2(JNIEnv* env, jclass clazz, jobject p0, jobject p1, jobject p2, jobject p3, jobject p4);
void Java_I__01160_0fe00_0fe04__0003cinit_0003e__Lbin_nt_main_PhotoViewerActivity_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_I__01160_0fe01_0fe02__0003cinit_0003e__Lbin_nt_main_MainActivity_2I(JNIEnv* env, jobject thiz, jobject p0, jint p1);
void Java_I__01160_0fe07_0fe02__0003cinit_0003e__Lbin_nt_main_MainActivity_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_I__01160_0fe07_0fe08__0003cinit_0003e__Lbin_nt_editor_widget_CodeEditor_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_I__01160_0fe08_0fe04__0003cinit_0003e__Lbin_nt_main_PhotoViewerActivity_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_I__01160_0fe09_0fe02__0003cinit_0003e__Lbin_nt_main_MainActivity_2Landroid_widget_FrameLayout_2Landroid_widget_FrameLayout_2(JNIEnv* env, jobject thiz, jobject p0, jobject p1, jobject p2);
void Java_I__01160_0fe09_0fe06__0003cinit_0003e__Lbin_nt_editor_widget_CodeEditor_2IIIII(JNIEnv* env, jobject thiz, jobject p0, jint p1, jint p2, jint p3, jint p4, jint p5);
void Java_I__01160_0fe09_0fe09__0003cinit_0003e__Lbin_nt_main_TextEditorActivity_2I(JNIEnv* env, jobject thiz, jobject p0, jint p1);
void Java_I__01160_0fe0a_0fe04__0003cinit_0003e__Lbin_nt_fragments_PreferenceFragment_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_I__01160_0fe0b_0fe04__0003cinit_0003e__Lbin_nt_fragments_PreferenceFragment_2Landroidx_preference_Preference_2I(JNIEnv* env, jobject thiz, jobject p0, jobject p1, jint p2);
void Java_I__01160_0fe0b_0fe09__0003cinit_0003e__Lbin_nt_main_TextEditorActivity_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_bin_nt_editor_widget_CodeEditor__0003cclinit_0003e__(JNIEnv* env, jclass clazz);
jint Java_bin_nt_editor_widget_CodeEditor_computeHorizontalScrollExtent__(JNIEnv* env, jobject thiz);
jint Java_bin_nt_editor_widget_CodeEditor_computeVerticalScrollExtent__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getAccessibilityClassName__(JNIEnv* env, jobject thiz);
jint Java_bin_nt_editor_widget_CodeEditor_getBlockIndex__(JNIEnv* env, jobject thiz);
jfloat Java_bin_nt_editor_widget_CodeEditor_getBlockLineWidth__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getClipboardManager__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getColorScheme__(JNIEnv* env, jobject thiz);
jint Java_bin_nt_editor_widget_CodeEditor_getCurrentCursorBlock__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getCursor__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getCursorAnimator__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getCursorBlink__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getCursorRange__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getDiagnosticIndicatorStyle__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getDiagnostics__(JNIEnv* env, jobject thiz);
jfloat Java_bin_nt_editor_widget_CodeEditor_getDividerMarginLeft__(JNIEnv* env, jobject thiz);
jfloat Java_bin_nt_editor_widget_CodeEditor_getDividerMarginRight__(JNIEnv* env, jobject thiz);
jfloat Java_bin_nt_editor_widget_CodeEditor_getDividerWidth__(JNIEnv* env, jobject thiz);
jfloat Java_bin_nt_editor_widget_CodeEditor_getDpUnit__(JNIEnv* env, jobject thiz);
jint Java_bin_nt_editor_widget_CodeEditor_getEdgeEffectColor__(JNIEnv* env, jobject thiz);
jboolean Java_bin_nt_editor_widget_CodeEditor_getEditable__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getEditorLanguage__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getEventHandler__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getExtraArguments__(JNIEnv* env, jobject thiz);
jint Java_bin_nt_editor_widget_CodeEditor_getFirstVisibleLine__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getFormatTip__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getGraphPaint__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getHandleStyle__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getHighlightTexts__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getHorizontalEdgeEffect__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getHorizontalScrollbarThumbDrawable__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getHorizontalScrollbarTrackDrawable__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getInlayHintRenderers__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getInlayHints__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getInputMethodManager__(JNIEnv* env, jobject thiz);
jint Java_bin_nt_editor_widget_CodeEditor_getInputType__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getInsertHandleDescriptor__(JNIEnv* env, jobject thiz);
jfloat Java_bin_nt_editor_widget_CodeEditor_getInsertSelectionWidth__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getKeyMetaStates__(JNIEnv* env, jobject thiz);
jint Java_bin_nt_editor_widget_CodeEditor_getLastVisibleLine__(JNIEnv* env, jobject thiz);
jint Java_bin_nt_editor_widget_CodeEditor_getLastVisibleRow__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getLayout__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getLeftHandleDescriptor__(JNIEnv* env, jobject thiz);
jint Java_bin_nt_editor_widget_CodeEditor_getLineCount__(JNIEnv* env, jobject thiz);
jfloat Java_bin_nt_editor_widget_CodeEditor_getLineInfoTextSize__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getLineNumberAlign__(JNIEnv* env, jobject thiz);
jfloat Java_bin_nt_editor_widget_CodeEditor_getLineNumberMarginLeft__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getLineNumberMetrics__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getLineNumberTipTextProvider__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getLineSeparator__(JNIEnv* env, jobject thiz);
jfloat Java_bin_nt_editor_widget_CodeEditor_getLineSpacingExtra__(JNIEnv* env, jobject thiz);
jfloat Java_bin_nt_editor_widget_CodeEditor_getLineSpacingMultiplier__(JNIEnv* env, jobject thiz);
jint Java_bin_nt_editor_widget_CodeEditor_getLineSpacingPixels__(JNIEnv* env, jobject thiz);
jint Java_bin_nt_editor_widget_CodeEditor_getLnPanelPosition__(JNIEnv* env, jobject thiz);
jint Java_bin_nt_editor_widget_CodeEditor_getLnPanelPositionMode__(JNIEnv* env, jobject thiz);
jint Java_bin_nt_editor_widget_CodeEditor_getNonPrintablePaintingFlags__(JNIEnv* env, jobject thiz);
jint Java_bin_nt_editor_widget_CodeEditor_getOffsetX__(JNIEnv* env, jobject thiz);
jint Java_bin_nt_editor_widget_CodeEditor_getOffsetY__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getOtherPaint__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getProps__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getRenderContext__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getRenderer__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getRightHandleDescriptor__(JNIEnv* env, jobject thiz);
jint Java_bin_nt_editor_widget_CodeEditor_getRowHeight__(JNIEnv* env, jobject thiz);
jint Java_bin_nt_editor_widget_CodeEditor_getRowHeightOfText__(JNIEnv* env, jobject thiz);
jint Java_bin_nt_editor_widget_CodeEditor_getScrollMaxX__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getScroller__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getSearcher__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getSelectingTarget__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getSnippetController__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getStyles__(JNIEnv* env, jobject thiz);
jint Java_bin_nt_editor_widget_CodeEditor_getTabWidth__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getText__(JNIEnv* env, jobject thiz);
jfloat Java_bin_nt_editor_widget_CodeEditor_getTextBorderWidth__(JNIEnv* env, jobject thiz);
jfloat Java_bin_nt_editor_widget_CodeEditor_getTextLetterSpacing__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getTextPaint__(JNIEnv* env, jobject thiz);
jfloat Java_bin_nt_editor_widget_CodeEditor_getTextScaleX__(JNIEnv* env, jobject thiz);
jfloat Java_bin_nt_editor_widget_CodeEditor_getTextSizePx__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getTypefaceLineNumber__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getTypefaceText__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getVerticalEdgeEffect__(JNIEnv* env, jobject thiz);
jfloat Java_bin_nt_editor_widget_CodeEditor_getVerticalExtraSpaceFactor__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getVerticalScrollbarThumbDrawable__(JNIEnv* env, jobject thiz);
jobject Java_bin_nt_editor_widget_CodeEditor_getVerticalScrollbarTrackDrawable__(JNIEnv* env, jobject thiz);
jboolean Java_bin_nt_editor_widget_CodeEditor_isHorizontalScrollBarEnabled__(JNIEnv* env, jobject thiz);
jboolean Java_bin_nt_editor_widget_CodeEditor_isVerticalScrollBarEnabled__(JNIEnv* env, jobject thiz);
void Java_bin_nt_editor_widget_CodeEditor_onConfigurationChanged__Landroid_content_res_Configuration_2(JNIEnv* env, jobject thiz, jobject p0);
jboolean Java_bin_nt_editor_widget_CodeEditor_onKeyMultiple__IILandroid_view_KeyEvent_2(JNIEnv* env, jobject thiz, jint p0, jint p1, jobject p2);
jboolean Java_bin_nt_editor_widget_CodeEditor_onKeyUp__ILandroid_view_KeyEvent_2(JNIEnv* env, jobject thiz, jint p0, jobject p1);
jboolean Java_bin_nt_editor_widget_CodeEditor_performAccessibilityAction__ILandroid_os_Bundle_2(JNIEnv* env, jobject thiz, jint p0, jobject p1);
jboolean Java_bin_nt_editor_widget_CodeEditor_removeCallbacks__Ljava_lang_Runnable_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_bin_nt_editor_widget_CodeEditor_setBlockLineEnabled__Z(JNIEnv* env, jobject thiz, jboolean p0);
void Java_bin_nt_editor_widget_CodeEditor_setBlockLineWidth__F(JNIEnv* env, jobject thiz, jfloat p0);
void Java_bin_nt_editor_widget_CodeEditor_setColorScheme__LI__0115f_0fe0c_0fe09_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_bin_nt_editor_widget_CodeEditor_setCursorAnimationEnabled__Z(JNIEnv* env, jobject thiz, jboolean p0);
void Java_bin_nt_editor_widget_CodeEditor_setCursorAnimator__LI__0115f_0fe06_0fe07_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_bin_nt_editor_widget_CodeEditor_setCursorBlinkPeriod__I(JNIEnv* env, jobject thiz, jint p0);
void Java_bin_nt_editor_widget_CodeEditor_setCursorWidth__F(JNIEnv* env, jobject thiz, jfloat p0);
void Java_bin_nt_editor_widget_CodeEditor_setDiagnosticIndicatorStyle__LI__0115f_0fe04_0fe08_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_bin_nt_editor_widget_CodeEditor_setDiagnostics__LI__0115f_0fe05_0fe08_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_bin_nt_editor_widget_CodeEditor_setDisableSoftKbdIfHardKbdAvailable__Z(JNIEnv* env, jobject thiz, jboolean p0);
void Java_bin_nt_editor_widget_CodeEditor_setDisplayLnPanel__Z(JNIEnv* env, jobject thiz, jboolean p0);
void Java_bin_nt_editor_widget_CodeEditor_setDividerMargin__F(JNIEnv* env, jobject thiz, jfloat p0);
void Java_bin_nt_editor_widget_CodeEditor_setDividerWidth__F(JNIEnv* env, jobject thiz, jfloat p0);
void Java_bin_nt_editor_widget_CodeEditor_setEdgeEffectColor__I(JNIEnv* env, jobject thiz, jint p0);
void Java_bin_nt_editor_widget_CodeEditor_setFirstLineNumberAlwaysVisible__Z(JNIEnv* env, jobject thiz, jboolean p0);
void Java_bin_nt_editor_widget_CodeEditor_setFontFeatureSettings__Ljava_lang_String_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_bin_nt_editor_widget_CodeEditor_setFormatTip__Ljava_lang_String_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_bin_nt_editor_widget_CodeEditor_setHardwareAcceleratedDrawAllowed__Z(JNIEnv* env, jobject thiz, jboolean p0);
void Java_bin_nt_editor_widget_CodeEditor_setHighlightBracketPair__Z(JNIEnv* env, jobject thiz, jboolean p0);
void Java_bin_nt_editor_widget_CodeEditor_setHighlightCurrentBlock__Z(JNIEnv* env, jobject thiz, jboolean p0);
void Java_bin_nt_editor_widget_CodeEditor_setHighlightCurrentLine__Z(JNIEnv* env, jobject thiz, jboolean p0);
void Java_bin_nt_editor_widget_CodeEditor_setHighlightTexts__LI__0115f_0fe09_0fe0f_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_bin_nt_editor_widget_CodeEditor_setHorizontalScrollBarEnabled__Z(JNIEnv* env, jobject thiz, jboolean p0);
void Java_bin_nt_editor_widget_CodeEditor_setHorizontalScrollbarThumbDrawable__Landroid_graphics_drawable_Drawable_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_bin_nt_editor_widget_CodeEditor_setHorizontalScrollbarTrackDrawable__Landroid_graphics_drawable_Drawable_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_bin_nt_editor_widget_CodeEditor_setInputType__I(JNIEnv* env, jobject thiz, jint p0);
void Java_bin_nt_editor_widget_CodeEditor_setLayoutBusy__Z(JNIEnv* env, jobject thiz, jboolean p0);
void Java_bin_nt_editor_widget_CodeEditor_setLineInfoTextSize__F(JNIEnv* env, jobject thiz, jfloat p0);
void Java_bin_nt_editor_widget_CodeEditor_setLineNumberAlign__Landroid_graphics_Paint_00024Align_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_bin_nt_editor_widget_CodeEditor_setLineNumberEnabled__Z(JNIEnv* env, jobject thiz, jboolean p0);
void Java_bin_nt_editor_widget_CodeEditor_setLineNumberMarginLeft__F(JNIEnv* env, jobject thiz, jfloat p0);
void Java_bin_nt_editor_widget_CodeEditor_setLineNumberTipTextProvider__LI__01160_0fe08_0fe01_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_bin_nt_editor_widget_CodeEditor_setLineSpacingExtra__F(JNIEnv* env, jobject thiz, jfloat p0);
void Java_bin_nt_editor_widget_CodeEditor_setLineSpacingMultiplier__F(JNIEnv* env, jobject thiz, jfloat p0);
void Java_bin_nt_editor_widget_CodeEditor_setLnPanelPosition__I(JNIEnv* env, jobject thiz, jint p0);
void Java_bin_nt_editor_widget_CodeEditor_setLnPanelPositionMode__I(JNIEnv* env, jobject thiz, jint p0);
void Java_bin_nt_editor_widget_CodeEditor_setNonPrintablePaintingFlags__I(JNIEnv* env, jobject thiz, jint p0);
void Java_bin_nt_editor_widget_CodeEditor_setPinLineNumber__Z(JNIEnv* env, jobject thiz, jboolean p0);
void Java_bin_nt_editor_widget_CodeEditor_setRenderFunctionCharacters__Z(JNIEnv* env, jobject thiz, jboolean p0);
void Java_bin_nt_editor_widget_CodeEditor_setScalable__Z(JNIEnv* env, jobject thiz, jboolean p0);
void Java_bin_nt_editor_widget_CodeEditor_setScrollBarEnabled__Z(JNIEnv* env, jobject thiz, jboolean p0);
void Java_bin_nt_editor_widget_CodeEditor_setSelectionHandleStyle__LI__01160_0fe0c_0fe06_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_bin_nt_editor_widget_CodeEditor_setSoftKeyboardEnabled__Z(JNIEnv* env, jobject thiz, jboolean p0);
void Java_bin_nt_editor_widget_CodeEditor_setStickyTextSelection__Z(JNIEnv* env, jobject thiz, jboolean p0);
void Java_bin_nt_editor_widget_CodeEditor_setStyles__LI__01160_0fe0e_0fe08_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_bin_nt_editor_widget_CodeEditor_setTabWidth__I(JNIEnv* env, jobject thiz, jint p0);
void Java_bin_nt_editor_widget_CodeEditor_setTextBorderWidth__F(JNIEnv* env, jobject thiz, jfloat p0);
void Java_bin_nt_editor_widget_CodeEditor_setTextLetterSpacing__F(JNIEnv* env, jobject thiz, jfloat p0);
void Java_bin_nt_editor_widget_CodeEditor_setTextScaleX__F(JNIEnv* env, jobject thiz, jfloat p0);
void Java_bin_nt_editor_widget_CodeEditor_setTextSizePx__F(JNIEnv* env, jobject thiz, jfloat p0);
void Java_bin_nt_editor_widget_CodeEditor_setTypefaceLineNumber__Landroid_graphics_Typeface_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_bin_nt_editor_widget_CodeEditor_setTypefaceText__Landroid_graphics_Typeface_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_bin_nt_editor_widget_CodeEditor_setUndoEnabled__Z(JNIEnv* env, jobject thiz, jboolean p0);
void Java_bin_nt_editor_widget_CodeEditor_setVerticalExtraSpaceFactor__F(JNIEnv* env, jobject thiz, jfloat p0);
void Java_bin_nt_editor_widget_CodeEditor_setVerticalScrollBarEnabled__Z(JNIEnv* env, jobject thiz, jboolean p0);
void Java_bin_nt_editor_widget_CodeEditor_setVerticalScrollbarThumbDrawable__Landroid_graphics_drawable_Drawable_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_bin_nt_editor_widget_CodeEditor_setVerticalScrollbarTrackDrawable__Landroid_graphics_drawable_Drawable_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_bin_nt_editor_widget_CodeEditor_setWordwrap__Z(JNIEnv* env, jobject thiz, jboolean p0);
void Java_bin_nt_editor_widget_CodeEditor__0115f_0fe01_0fe00__(JNIEnv* env, jobject thiz);
void Java_bin_nt_editor_widget_CodeEditor__0115f_0fe01_0fe03__(JNIEnv* env, jobject thiz);
void Java_bin_nt_editor_widget_CodeEditor__0115f_0fe01_0fe04__IIII(JNIEnv* env, jobject thiz, jint p0, jint p1, jint p2, jint p3);
void Java_bin_nt_editor_widget_CodeEditor__0115f_0fe02_0fe01__LI__0115f_0fe0d_0fe06_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_bin_nt_editor_widget_CodeEditor__0115f_0fe02_0fe03__I(JNIEnv* env, jobject thiz, jint p0);
jboolean Java_bin_nt_editor_widget_CodeEditor__0115f_0fe03_0fe00__(JNIEnv* env, jobject thiz);
jlong Java_bin_nt_editor_widget_CodeEditor__0115f_0fe03_0fe02__FF(JNIEnv* env, jobject thiz, jfloat p0, jfloat p1);
jboolean Java_bin_nt_editor_widget_CodeEditor__0115f_0fe03_0fe03__IILandroid_view_KeyEvent_2(JNIEnv* env, jobject thiz, jint p0, jint p1, jobject p2);
void Java_bin_nt_editor_widget_CodeEditor__0115f_0fe03_0fe04__ZZ(JNIEnv* env, jobject thiz, jboolean p0, jboolean p1);
jlong Java_bin_nt_editor_widget_CodeEditor__0115f_0fe04_0fe02__FF(JNIEnv* env, jobject thiz, jfloat p0, jfloat p1);
jboolean Java_bin_nt_editor_widget_CodeEditor__0115f_0fe04_0fe03__ILandroid_view_KeyEvent_2(JNIEnv* env, jobject thiz, jint p0, jobject p1);
void Java_bin_nt_editor_widget_CodeEditor__0115f_0fe04_0fe04__(JNIEnv* env, jobject thiz);
void Java_bin_nt_editor_widget_CodeEditor__0115f_0fe05_0fe03__(JNIEnv* env, jobject thiz);
void Java_bin_nt_editor_widget_CodeEditor__0115f_0fe06_0fe00__Z(JNIEnv* env, jobject thiz, jboolean p0);
void Java_bin_nt_editor_widget_CodeEditor__0115f_0fe06_0fe03__Ljava_lang_String_2(JNIEnv* env, jobject thiz, jobject p0);
jfloat Java_bin_nt_editor_widget_CodeEditor__0115f_0fe06_0fe04__(JNIEnv* env, jobject thiz);
void Java_bin_nt_editor_widget_CodeEditor__0115f_0fe08_0fe00__IILjava_lang_CharSequence_2(JNIEnv* env, jobject thiz, jint p0, jint p1, jobject p2);
void Java_bin_nt_editor_widget_CodeEditor__0115f_0fe08_0fe03__Ljava_lang_Runnable_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_bin_nt_editor_widget_CodeEditor__0115f_0fe09_0fe01__(JNIEnv* env, jobject thiz);
jboolean Java_bin_nt_editor_widget_CodeEditor__0115f_0fe09_0fe02__(JNIEnv* env, jobject thiz);
void Java_bin_nt_editor_widget_CodeEditor__0115f_0fe09_0fe03__(JNIEnv* env, jobject thiz);
void Java_bin_nt_editor_widget_CodeEditor__0115f_0fe0a_0fe02__(JNIEnv* env, jobject thiz);
void Java_bin_nt_editor_widget_CodeEditor__0115f_0fe0a_0fe03__(JNIEnv* env, jobject thiz);
jboolean Java_bin_nt_editor_widget_CodeEditor__0115f_0fe0b_0fe02__(JNIEnv* env, jobject thiz);
void Java_bin_nt_editor_widget_CodeEditor__0115f_0fe0b_0fe03__(JNIEnv* env, jobject thiz);
void Java_bin_nt_editor_widget_CodeEditor__0115f_0fe0d_0fe03__II(JNIEnv* env, jobject thiz, jint p0, jint p1);
jfloat Java_bin_nt_editor_widget_CodeEditor__0115f_0fe0e_0fe02__(JNIEnv* env, jobject thiz);
void Java_bin_nt_editor_widget_CodeEditor__0115f_0fe0e_0fe03__FF(JNIEnv* env, jobject thiz, jfloat p0, jfloat p1);
void Java_bin_nt_editor_widget_CodeEditor__0115f_0fe0f_0fe01__(JNIEnv* env, jobject thiz);
void Java_bin_nt_editor_widget_CodeEditor__0115f_0fe0f_0fe02__LI__01160_0fe0e_0fe06_2Z(JNIEnv* env, jobject thiz, jobject p0, jboolean p1);
void Java_bin_nt_editor_widget_CodeEditor__0115f_0fe0f_0fe03__II(JNIEnv* env, jobject thiz, jint p0, jint p1);
void Java_bin_nt_ui_HackyViewPager__0003cinit_0003e__Landroid_content_Context_2Landroid_util_AttributeSet_2(JNIEnv* env, jobject thiz, jobject p0, jobject p1);
jboolean Java_bin_nt_ui_HackyViewPager_onInterceptTouchEvent__Landroid_view_MotionEvent_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_bin_nt_ui_jellyrefresh_JellyRefreshLayout__0003cinit_0003e__Landroid_content_Context_2Landroid_util_AttributeSet_2(JNIEnv* env, jobject thiz, jobject p0, jobject p1);
void Java_bin_nt_ui_jellyrefresh_JellyRefreshLayout_setJellyColor__I(JNIEnv* env, jobject thiz, jint p0);
void Java_bin_nt_ui_jellyrefresh_JellyRefreshLayout_setLoadingView__Landroid_view_View_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_bin_nt_ui_jellyrefresh_JellyRefreshLayout_setSweepDirection__Z(JNIEnv* env, jobject thiz, jboolean p0);
void Java_bin_nt_ui_jellyrefresh_JellyRefreshLayout__0115f_0fe03_0fe00__LI__01160_0fe0a_0fe00_2F(JNIEnv* env, jobject thiz, jobject p0, jfloat p1);
jfloat Java_bin_nt_ui_jellyrefresh_JellyRefreshLayout__0115f_0fe04_0fe00__F(JNIEnv* env, jobject thiz, jfloat p0);
void Java_I__0115f_0fe0a_0fe00__0003cinit_0003e__Lbin_nt_editor_widget_CodeEditor_2LI__0115f_0fe0d_0fe06_2(JNIEnv* env, jobject thiz, jobject p0, jobject p1);
void Java_I__01160_0fe02_0fe04__0003cinit_0003e__Lbin_nt_main_PhotoViewerActivity_2(JNIEnv* env, jobject thiz, jobject p0);
jobject Java_bin_nt_fragments_FileBrowserFragment__0115f_0fe07_0fe05__Ljava_lang_String_2(JNIEnv* env, jclass clazz, jobject p0);
jobject Java_bin_nt_fragments_FileBrowserFragment__0115f_0fe09_0fe04__LI__0115f_0fe0e_0fe0e_2(JNIEnv* env, jclass clazz, jobject p0);
jobject Java_bin_nt_fragments_FileBrowserFragment__0115f_0fe0f_0fe04__Landroid_content_SharedPreferences_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2(JNIEnv* env, jclass clazz, jobject p0, jobject p1, jobject p2, jobject p3);
void Java_bin_nt_fragments_FileBrowserFragment__0115f_0fe00_0fe02__(JNIEnv* env, jobject thiz);
void Java_bin_nt_fragments_FileBrowserFragment__0115f_0fe00_0fe05__(JNIEnv* env, jobject thiz);
void Java_bin_nt_fragments_FileBrowserFragment__0115f_0fe01_0fe04__(JNIEnv* env, jobject thiz);
void Java_bin_nt_fragments_FileBrowserFragment__0115f_0fe01_0fe05__LI__0115f_0fe0e_0fe0e_2Ljava_lang_String_2Landroid_content_Context_2Ljava_lang_String_2(JNIEnv* env, jobject thiz, jobject p0, jobject p1, jobject p2, jobject p3);
jboolean Java_bin_nt_fragments_FileBrowserFragment__0115f_0fe02_0fe04__(JNIEnv* env, jobject thiz);
void Java_bin_nt_fragments_FileBrowserFragment__0115f_0fe03_0fe04__ZZ(JNIEnv* env, jobject thiz, jboolean p0, jboolean p1);
void Java_bin_nt_fragments_FileBrowserFragment__0115f_0fe03_0fe05__I(JNIEnv* env, jobject thiz, jint p0);
void Java_bin_nt_fragments_FileBrowserFragment__0115f_0fe04_0fe02__(JNIEnv* env, jobject thiz);
void Java_bin_nt_fragments_FileBrowserFragment__0115f_0fe04_0fe04__Ljava_lang_String_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_bin_nt_fragments_FileBrowserFragment__0115f_0fe05_0fe04__LI__0115f_0fe0e_0fe0e_2Z(JNIEnv* env, jobject thiz, jobject p0, jboolean p1);
jobject Java_bin_nt_fragments_FileBrowserFragment__0115f_0fe05_0fe05__Ljava_lang_String_2Z(JNIEnv* env, jobject thiz, jobject p0, jboolean p1);
void Java_bin_nt_fragments_FileBrowserFragment__0115f_0fe06_0fe02__Landroid_os_Bundle_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_bin_nt_fragments_FileBrowserFragment__0115f_0fe07_0fe02__(JNIEnv* env, jobject thiz);
void Java_bin_nt_fragments_FileBrowserFragment__0115f_0fe08_0fe02__(JNIEnv* env, jobject thiz);
void Java_bin_nt_fragments_FileBrowserFragment__0115f_0fe08_0fe04__LI__0115f_0fe0e_0fe0e_2(JNIEnv* env, jobject thiz, jobject p0);
jboolean Java_bin_nt_fragments_FileBrowserFragment__0115f_0fe0b_0fe03__(JNIEnv* env, jobject thiz);
void Java_bin_nt_fragments_FileBrowserFragment__0115f_0fe0c_0fe03__(JNIEnv* env, jobject thiz);
void Java_bin_nt_fragments_FileBrowserFragment__0115f_0fe0c_0fe04__ILjava_lang_String_2(JNIEnv* env, jobject thiz, jint p0, jobject p1);
void Java_bin_nt_fragments_FileBrowserFragment__0115f_0fe0d_0fe03__ILjava_util_List_2(JNIEnv* env, jobject thiz, jint p0, jobject p1);
void Java_bin_nt_fragments_FileBrowserFragment__0115f_0fe0d_0fe04__(JNIEnv* env, jobject thiz);
void Java_bin_nt_fragments_FileBrowserFragment__0115f_0fe0f_0fe03__(JNIEnv* env, jobject thiz);
void Java_bin_nt_fragments_PreferenceFragment__0115f_0fe00_0fe02__(JNIEnv* env, jobject thiz);
void Java_bin_nt_fragments_PreferenceFragment__0115f_0fe0c_0fe03__Landroidx_preference_Preference_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_bin_nt_fragments_PreferenceFragment__0115f_0fe0e_0fe01__Landroid_os_Bundle_2(JNIEnv* env, jobject thiz, jobject p0);
jobject Java_bin_nt_fragments_PreferenceFragment__0115f_0fe0f_0fe01__Landroid_view_LayoutInflater_2Landroid_view_ViewGroup_2Landroid_os_Bundle_2(JNIEnv* env, jobject thiz, jobject p0, jobject p1, jobject p2);
void Java_bin_nt_main_EditorPreferencesActivity_00024EditorPreferenceFragment__0003cinit_0003e__(JNIEnv* env, jobject thiz);
void Java_bin_nt_main_EditorPreferencesActivity_00024EditorPreferenceFragment__0115f_0fe0a_0fe03__Ljava_lang_String_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_bin_nt_ui_fastscroll_FastScrollerRecyclerView__0003cinit_0003e__Landroid_content_Context_2Landroid_util_AttributeSet_2(JNIEnv* env, jobject thiz, jobject p0, jobject p1);
jboolean Java_bin_nt_ui_fastscroll_FastScrollerRecyclerView_onInterceptTouchEvent__Landroid_view_MotionEvent_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_bin_nt_ui_fastscroll_FastScrollerRecyclerView_setLayoutManager__Landroidx_recyclerview_widget_RecyclerView_00024LayoutManager_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_bin_nt_ui_fastscroll_FastScrollerRecyclerView_setTrackVisible__Z(JNIEnv* env, jobject thiz, jboolean p0);
void Java_bin_nt_main_BaseActivity__0115f_0fe05_0fe01__(JNIEnv* env, jobject thiz);
void Java_bin_nt_main_CrashActivity__0003cclinit_0003e__(JNIEnv* env, jclass clazz);
void Java_bin_nt_main_CrashActivity__0003cinit_0003e__(JNIEnv* env, jobject thiz);
void Java_bin_nt_main_CrashActivity__0115f_0fe05_0fe01__(JNIEnv* env, jobject thiz);
void Java_bin_nt_main_CrashActivity__0115f_0fe0d_0fe01__(JNIEnv* env, jobject thiz);
void Java_bin_nt_main_EditorPreferencesActivity__0003cinit_0003e__(JNIEnv* env, jobject thiz);
jboolean Java_bin_nt_main_MainActivity__0115f_0fe01_0fe02__Landroid_content_Intent_2(JNIEnv* env, jclass clazz, jobject p0);
void Java_bin_nt_main_MainActivity_onBackPressed__(JNIEnv* env, jobject thiz);
void Java_bin_nt_main_MainActivity__0115f_0fe02_0fe02__(JNIEnv* env, jobject thiz);
void Java_bin_nt_main_MainActivity__0115f_0fe04_0fe02__(JNIEnv* env, jobject thiz);
void Java_bin_nt_main_MainActivity__0115f_0fe05_0fe01__(JNIEnv* env, jobject thiz);
void Java_bin_nt_main_MainActivity__0115f_0fe05_0fe02__(JNIEnv* env, jobject thiz);
void Java_bin_nt_main_MainActivity__0115f_0fe07_0fe02__Z(JNIEnv* env, jobject thiz, jboolean p0);
jobject Java_bin_nt_main_MainActivity__0115f_0fe0e_0fe01__I(JNIEnv* env, jobject thiz, jint p0);
jboolean Java_bin_nt_main_PhotoViewerActivity_onKeyDown__ILandroid_view_KeyEvent_2(JNIEnv* env, jobject thiz, jint p0, jobject p1);
void Java_bin_nt_main_PhotoViewerActivity_onResume__(JNIEnv* env, jobject thiz);
void Java_bin_nt_main_PhotoViewerActivity__0115f_0fe00_0fe02__(JNIEnv* env, jobject thiz);
void Java_bin_nt_main_PhotoViewerActivity__0115f_0fe01_0fe02__F(JNIEnv* env, jobject thiz, jfloat p0);
void Java_bin_nt_main_PhotoViewerActivity__0115f_0fe0f_0fe01__(JNIEnv* env, jobject thiz);
void Java_bin_nt_main_Preferences__0003cinit_0003e__(JNIEnv* env, jobject thiz);
jboolean Java_bin_nt_main_Preferences_onOptionsItemSelected__Landroid_view_MenuItem_2(JNIEnv* env, jobject thiz, jobject p0);
void Java_bin_nt_main_Preferences__0115f_0fe05_0fe01__(JNIEnv* env, jobject thiz);
void Java_bin_nt_main_TextEditorActivity_onBackPressed__(JNIEnv* env, jobject thiz);
void Java_bin_nt_main_TextEditorActivity_onContentChanged__(JNIEnv* env, jobject thiz);
void Java_bin_nt_main_TextEditorActivity__0115f_0fe00_0fe02__I(JNIEnv* env, jobject thiz, jint p0);
void Java_bin_nt_main_TextEditorActivity__0115f_0fe01_0fe02__(JNIEnv* env, jobject thiz);
void Java_bin_nt_main_TextEditorActivity__0115f_0fe02_0fe02__(JNIEnv* env, jobject thiz);
void Java_bin_nt_main_TextEditorActivity__0115f_0fe03_0fe02__(JNIEnv* env, jobject thiz);
void Java_bin_nt_main_TextEditorActivity__0115f_0fe04_0fe02__(JNIEnv* env, jobject thiz);
void Java_bin_nt_main_TextEditorActivity__0115f_0fe05_0fe01__(JNIEnv* env, jobject thiz);
void Java_bin_nt_main_TextEditorActivity__0115f_0fe05_0fe02__Z(JNIEnv* env, jobject thiz, jboolean p0);
void Java_bin_nt_main_TextEditorActivity__0115f_0fe06_0fe02__(JNIEnv* env, jobject thiz);
void Java_bin_nt_main_TextEditorActivity__0115f_0fe07_0fe02__(JNIEnv* env, jobject thiz);
void Java_bin_nt_main_TextEditorActivity__0115f_0fe0d_0fe01__Ljava_lang_String_2(JNIEnv* env, jobject thiz, jobject p0);

#endif
